# Creación de arrays en NumPy🧩

In [4]:
import numpy as np
print(f'Versión de la librería usada: {np.__version__}')

Versión de la librería usada: 2.3.5


## 1. La función más importante de NumPy: ```np.array()``` 🧱
```np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)```

 - __Object:__ Es el objeto iterable de entrada que queremos convertir en un array de Numpy 
 - __dtype:__ Indica el tipo de dato del array. Si se pone el tipo de datos, Numpy lo infiere automáticamente.
 - __copy:__ Define su NumPy copia los datos o solo usa la referencia.
 - __Order:__ Define como se ordenan los datos en memoria.
 - __subok:__ Indica si NumPy debe permitir subclases de ```ndarray```.
 - __ndmin:__ Define en número mínimo de dimensiones que tendrá el array.

## 1.1. Creación desde listas o tuplas🟢

In [14]:
# Lista 1D -> Array 2D
lista = range(20, 30)
array_1d = np.array(lista)
print(f'Array NumPy:\n{array_1d}')
print('-' * 40)
# Atributos que nos permiten ver las características del array de NumPy
print(f'Dimesiones: {array_1d.shape}\nTipo de datos del array: {array_1d.dtype}')

Array NumPy:
[20 21 22 23 24 25 26 27 28 29]
----------------------------------------
Dimesiones: (10,)
Tipo de datos del array: int64


In [15]:
# Lista anidada -> array 2D
datos_ventas= [
    [101, "2025-01-01", 1250.5],
    [102, "2025-01-02", 1890.0],
    [103, "2025-01-03", 1670.4]
]
ventas_array = np.array(datos_ventas)
print(f'Array 2D de NumPy:\n{ventas_array}')
print('-' * 40)
print(f'Dimesiones: {ventas_array.shape}\nTipo de dato: {ventas_array.dtype}')

Array 2D de NumPy:
[['101' '2025-01-01' '1250.5']
 ['102' '2025-01-02' '1890.0']
 ['103' '2025-01-03' '1670.4']]
----------------------------------------
Dimesiones: (3, 3)
Tipo de dato: <U32


__NOTA💡:__ Si mezclamos tipos de datos diferentes (```int```+ ```srt```), NumPy fuerza todo a ```object(``` o ```String```.

## 1.2. Forzar el tipo de datos (```dtype```)✍️

In [24]:
# ✅ Separar columnas o forzar tipos
ids = np.array([101, 103, 104], dtype= np.int32)
fechas = np.array(["2025-01-01", "2025-01-02", "2025-01-03"], dtype='U10')  # Unicode 10 chars
importes = np.array([1250.5, 1890.0, 1670.75], dtype=np.float64)
print(f'Ids:\n{ids}')
print('-' * 45)
print(f'Fechas:\n{fechas}')
print('-' * 45)
print(f'Importes:\n{importes}')  

Ids:
[101 103 104]
---------------------------------------------
Fechas:
['2025-01-01' '2025-01-02' '2025-01-03']
---------------------------------------------
Importes:
[1250.5  1890.   1670.75]


In [25]:
# KPIs
print(f'Ingreso total: {importes.sum()}')
print(f'Media diaria: {importes.mean()}')

Ingreso total: 4811.25
Media diaria: 1603.75


In [29]:
# Dtypes para fechas
fechas_np = np.array(fechas, dtype = "datetime64[D]")
print(f'Array NumPy de fechas:\n{fechas_np}')

Array NumPy de fechas:
['2025-01-01' '2025-01-02' '2025-01-03']


In [31]:
#Forzar dimesiones (ndadmin)-últil para broadcasting futuro
vector = np.array(range(1,5), ndmin= 2) # -> shape (1, 4) en vez de (4,)
matriz = np.array([range(1,3), range(3, 5)], ndmin= 3)
print(f'Dimesiones del vector: {vector.shape}')
print(f'Dimesiones de la matriz: {matriz.shape}')

Dimesiones del vector: (1, 4)
Dimesiones de la matriz: (1, 2, 2)


## 1.3. Arrays prerellenados✅
Firmas de los métodos a usar:
```
np.zeros(shape, dtype=float, order='C')
np.ones(shape, dtype=None, order='C')
np.full(shape, fill_value, dtype=None, order='C')
```

### 1.3.1. Inicializar acumuladores o contadores: ```zeros()```

In [39]:
#Array para inicializar contadores o aculumuladores
acumulador_mensual = np.zeros(12, dtype= np.float64) #12 meses
print(f'Acumulador mensual:\n{acumulador_mensual}')

Acumulador mensual:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [40]:
#Matriz para resultados (por ejemplo 100 clientes x 5 métricas)
matriz_resultados = np.zeros((80 , 5), dtype = np.float64)
print(f'Matriz de resultados (80 clientes por 5 métricas):\n{matriz_resultados}')

Matriz de resultados (80 clientes por 5 métricas):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0.

### 1.3.2. Multiplicación rapida o inicializar probabilidades: ```ones()```✨

In [41]:
# Array de unos para multiplicar
precios_unitarios = np.ones(50, dtype= np.float64) 
print(f'Array para los precios unitarios:\n{precios_unitarios}')

Array para los precios unitarios:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [42]:
# Matriz de probabilidades iniciales
probabilidades = np.ones((10, 4), dtype= np.float64)
print(f'Matriz para probabilidades iniciales:\n{probabilidades}')

Matriz para probabilidades iniciales:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 1.3.3. Arreglo con un valor constante definido: ```full()```✍️

In [47]:
# Valores missing (ausencia de datos real) o sentinelas (Indicar el estado o condición de un elememnto dentro de un conjuto de datos)
missing = np.full(100, fill_value= np.nan)
missing_int_missing = np.full(100, fill_value= -999)

print(f'Primer array:\n{missing}')
print('=' * 80)
print(f'Segundo array:\n{missing_int_missing}')

Primer array:
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan]
Segundo array:
[-999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999
 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999
 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999
 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999
 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999
 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999
 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999 -999
 -999 -999]


In [49]:
#Inicializar categorias
categorias = np.full(50, fill_value= "Sin_categoria", dtype = "U20")
print(f'Array para categorias:\n{categorias}')

Array para categorias:
['Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria' 'Sin_categoria' 'Sin_categoria'
 'Sin_categoria' 'Sin_categoria']


In [51]:
# Precio con valor por defecto
precios = np.full((500, 3), fill_value= 0.0)
# 500 productos para tres tiendas
print(f'matriz de precios:\n{precios}')

matriz de precios:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 ...
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


##  1.4. Creación de arreglos sin inicializar valores: Método ```np.empty()```🕵️
Crear un array sin incializar sus valores, usarlo cuando vayamos a __sobreescribir__ __todos__ los valores __inmediatamente__.
```
numpy.empty(shape, dtype=float, order='C', like=None)
```


In [55]:
temp = np.empty(1_000, dtype= np.float64)
for i in range(1_000):
    temp[i] = i + 1

print(f'Array "temp":\n{temp}')

Array "temp":
[   1.    2.    3.    4.    5.    6.    7.    8.    9.   10.   11.   12.
   13.   14.   15.   16.   17.   18.   19.   20.   21.   22.   23.   24.
   25.   26.   27.   28.   29.   30.   31.   32.   33.   34.   35.   36.
   37.   38.   39.   40.   41.   42.   43.   44.   45.   46.   47.   48.
   49.   50.   51.   52.   53.   54.   55.   56.   57.   58.   59.   60.
   61.   62.   63.   64.   65.   66.   67.   68.   69.   70.   71.   72.
   73.   74.   75.   76.   77.   78.   79.   80.   81.   82.   83.   84.
   85.   86.   87.   88.   89.   90.   91.   92.   93.   94.   95.   96.
   97.   98.   99.  100.  101.  102.  103.  104.  105.  106.  107.  108.
  109.  110.  111.  112.  113.  114.  115.  116.  117.  118.  119.  120.
  121.  122.  123.  124.  125.  126.  127.  128.  129.  130.  131.  132.
  133.  134.  135.  136.  137.  138.  139.  140.  141.  142.  143.  144.
  145.  146.  147.  148.  149.  150.  151.  152.  153.  154.  155.  156.
  157.  158.  159.  160.  161.  162. 